name: flutter_base
description: Base Function App
version: 1.0.3+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  fluttertoast: 8.0.9
  shared_preferences: 2.0.15
  html: 0.15.0
  intl: 0.17.0
  tuple: 2.0.0
  shimmer: 2.0.0
  crypto: 3.0.1
  url_launcher: 6.1.7
  logger: ^1.1.0
  uni_links: 0.5.1
  flutter_secure_storage: 6.0.0
  uuid: 3.0.6
  encrypt: 5.0.0
  path_provider: 2.0.15
  device_info: 2.0.3
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true



